### ISSUE TITLE
sublime with adaptive UI - captain sweetheart theme

### ISSUE THREAD

**Issue by gurqn** [mashaal/hyper-captain-sweetheart#1]
Would it be possible the developing sublimetext variant of this hyper theme? It would be great :)

**Comment by gurqn** [comment]
anyone there? :)

**Comment by mashaal** [comment]
Thanks @gurqn -- I agree this would be a great idea. I have been out of the loop with sublime themes. There is an ATOM variation here https://github.com/mashaal/atom-captain-sweetheart. Maybe someone can use this to convert to Sublime?

**Comment by gurqn** [comment]
Ah, thanks a lot. I'm aware of this theme. I think I know someone who would like to do that :)

@e1ectron

https://github.com/e1ectron/sublime-pastels-ui/issues/1
